MuchoMasFacil\InPageEditBundle\Entity\Content:
    type: entity
    repositoryClass: MuchoMasFacil\InPageEditBundle\Entity\ContentRepository
    table: null
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ipe_handler: {type: string, length: 255, gedmo: ['sortableGroup']}
        ipe_position: {type: integer, gedmo: ['sortablePosition']}
        header: {type: string, length: 255}
        content: {type: text}
    lifecycleCallbacks: {}
        #prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
