MuchoMasFacil\InPageEditBundle\Entity\Content:
    type: entity
    repositoryClass: MuchoMasFacil\InPageEditBundle\Entity\ContentRepository
    table: null
    id:
        handler:
            type: string
            length: 255
            id: true
            generator:
                strategy: NONE
    fields:
        content_entity_class: {type: string, length: 255}
        editor_roles: {type: text}
        is_collection: {type: boolean}
        max_collection_length: {type: integer, nullable: true}
        content: {type: array, nullable: true}
    lifecycleCallbacks: {}
        #prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
