MuchoMasFacil\InPageEditBundle\Entity\Foo:
    type: entity
    repositoryClass: MuchoMasFacil\InPageEditBundle\Entity\FooRepository
    table: null
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name: {type: string, length: 255}
        address: {type: string, length: 255}
        phone_number: {type: string, length: 255}
        company: {type: string, length: 255}
        email: {type: string, length: 255}
        url: {type: string, length: 255}
        datetime: {type: datetime}
        date: {type: date}
        time: {type: time}
        text: {type: text, nullable: true}        
    lifecycleCallbacks: {}

