MuchoMasFacil\InPageEditBundle\Entity\GroupedSortedMappedHeaderTextImage:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        string: { type: string, required: false }
        text: { type: text, required: false }
        image: { type: image, required: false }
        #next fields are what makes a grouped, sorted, mapped entity
        ipe_handler: {type: string, length: 255, gedmo: ['sortableGroup']}
        ipe_position: {type: integer, gedmo: ['sortablePosition']}
    lifecycleCallbacks: {  }    
