parameters:
    mucho_mas_facil_in_page_edit.definitions:

        orm_doctrine_mapped_entity: # doctrine_mapped_entity
            alias: odme
            ipe_controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/MappedEntity
            editor_roles: [] # ROLE_IPE_EDITOR # optional
            container_html_tag: div # optional
            container_html_attributes: '' # optional
            find_params:
                # in this definition normally, you pass an entity rather than find by params
                - entity_class: ~ # guessed from entity
                - find_by_array: ~ # guessed from entity
            params:
                entity_class: ~ # guessed from definition or by parameter
                form_type_class: ~ # guessed either from definition or by parameter
                render_template: ~ # if not set will be guessed from entity_class

        orm_doctrine_grouped_sorted_mapped_entity_collection:
            alias: odgsmec
            ipe_controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/GroupedSortedMappedEntityCollection
            editor_roles: [] # ROLE_IPE_EDITOR # optional
            find_params:
                # in this definition normally, you will propable pass find_params rather than an object or array collection of objects
                - entity_class: ~ # required YourCustomBundle:YourEntity
                - find_by_array: ~ # required; propable array('ipe_handler' => 'your-custom-handler')
                - order_by_array: { ipe_position: ASC }
                - is_collection: ~ # required boolean
            params:
                entity_class: ~ # required ??
                ipe_handler_field_value: ~ # required ??
                is_collection: true # required ??
                list_to_string_method: __toString
                max_collection_length: ~
                collection_ipe_handler_field: ipe_handler
                collection_ipe_position_field: ipe_position

        orm_doctrine_grouped_sorted_object_collection:
            alias: odgsoc
            ipe_controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/GroupedSortedObjectCollection
            editor_roles: [] # ROLE_IPE_EDITOR # optional
            find_params:
                # in this definition normally, you will propable pass find_params rather than an object or array collection of objects
                - entity_class: ~ # required YourCustomBundle:YourEntity
                - find_by_array: ~ # required; propable array('ipe_handler' => 'your-custom-handler')
                - order_by_array: { ipe_position: ASC }
                - is_collection: ~ # required boolean
            params:
                object_class: ~ # required ??
                ipe_handler_field_value: ~ # required ??
                is_collection: true # required ??
                list_to_string_method: __toString
                max_collection_length: ~
                collection_ipe_handler_field: ipe_handler
                collection_ipe_position_field: ipe_position

