_ipe_action:
    pattern:  /ipe/{action}/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipe}

_ipe_locale:
    pattern:  /ipe/locale/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipeSetLocale}

_ipe_navbar:
    pattern:  /ipe/navbar/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:_navbar}
