# InPageEdit doctrine routes
ipe_set_locale:
    pattern:  /ipe_set_locale/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:setIpeLocale}

ipe_doctrine_render:
    pattern:  /ipe_doctrine_render/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:ajaxRender}
    options:
        expose: true

ipe_doctrine_edit_index:
    pattern:  /ipe_doctrine_edit_index/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:editIndex}
    options:
        expose: true

ipe_doctrine_edit:
    pattern:  /ipe_doctrine_edit/{ipe_hash}/{action_on_success}/{id}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:edit, action_on_success: none, id: null}
    options:
        expose: true

ipe_doctrine_collection_list:
    pattern:  /ipe_doctrine_collection_list/{ipe_hash}/{reload_content}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionList, reload_content: false}
    options:
        expose: true

ipe_doctrine_collection_sort:
    pattern:  /ipe_doctrine_collection_sort/{ipe_hash}/{id}/{position}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionSort}
    options:
        expose: true

ipe_doctrine_collection_add_item:
    pattern:  /ipe_doctrine_collection_add_item/{ipe_hash}/{position}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionAddItem}
    options:
        expose: true

ipe_doctrine_collection_delete_item:
    pattern:  /ipe_doctrine_collection_delete_item/{ipe_hash}/{id}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionDeleteItem}
    options:
        expose: true    