_ipe_action:
    pattern:  /ipe/{action}/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipe}
    options:
        expose: true

_ipe_locale:
    pattern:  /ipe_locale/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipeSetLocale}

_ipe_mmf_ajax_modal_helper:
    path: /ipe_mmf_ajax_modal_helper.js
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'MuchoMasFacilInPageEditBundle:IPE:mmfAjaxModalHelpers.js.twig'


ipe_navbar:
    pattern:  /ipe_navbar/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:_navbar}
