_ipe_action:
    pattern:  /ipe/{action}/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipe}
    options:
        expose: true

_ipe_locale:
    pattern:  /ipe_locale/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipeSetLocale}

_ipe_mmf_ajax_modal_helper:
    path: /ipe_mmf_ajax_modal_helper.js
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'MuchoMasFacilInPageEditBundle:IPE:mmfAjaxModalHelpers.js.twig'

#routes for doctrine_orm_entity
ipe_doe_edit:
    pattern:  /ipe_doe_edit/{ipe_hash}/{action_on_success}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/Entity:edit, action_on_success: none}
    options:
        expose: true

ipe_doe_remove:
    pattern:  /ipe_doe_remove/{ipe_hash}/{action_on_success}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/Entity:remove, action_on_success: none}
    options:
        expose: true





# InPageEdit doctrine NOT secured routes
_ipe_doctrine_render:
    pattern:  /ipe_doctrine_render/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:ajaxRender}
    options:
        expose: true

# InPageEdit doctrine secured routes
ipe_navbar:
    pattern:  /ipe_navbar/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:_navbar}

ipe_doctrine_edit_index:
    pattern:  /ipe_doctrine_edit_index/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:editIndex}
    options:
        expose: true



ipe_doctrine_collection_list:
    pattern:  /ipe_doctrine_collection_list/{ipe_hash}/{reload_content}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionList, reload_content: false}
    options:
        expose: true

ipe_doctrine_collection_sort:
    pattern:  /ipe_doctrine_collection_sort/{ipe_hash}/{id}/{position}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionSort}
    options:
        expose: true

ipe_doctrine_collection_add_item:
    pattern:  /ipe_doctrine_collection_add_item/{ipe_hash}/{position}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionAddItem}
    options:
        expose: true

ipe_doctrine_collection_delete_item:
    pattern:  /ipe_doctrine_collection_delete_item/{ipe_hash}/{id}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:collectionDeleteItem}
    options:
        expose: true
