_ipe_action:
    pattern:  /ipe/{action}/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipe}

_ipe_locale:
    pattern:  /ipe_locale/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipeSetLocale}

ipe_navbar:
    pattern:  /ipe_navbar/{locale}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:ORM/Doctrine/InPageEdit:_navbar}
