_ipe_navbar:
    pattern:  /ipe/navbar/{locale}/{template}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:_navbar}

_ipe_action:
    pattern:  /ipe/{action}/{ipe_hash}
    defaults: { _controller: MuchoMasFacilInPageEditBundle:IPE:ipe}


