parameters:

    mucho_mas_facil_in_page_edit.available_langs:
        en: {label: English}
        es: {label: Español}

    mucho_mas_facil_in_page_edit.message_catalog: ipe_messages

    mucho_mas_facil_in_page_edit.twig.ipe_extension.class: MuchoMasFacil\InPageEditBundle\Twig\IpeExtension
    mucho_mas_facil_in_page_edit.twig.ipe_extension.doctrine.orm.faker.class: MuchoMasFacil\InPageEditBundle\Twig\IpeExtensionDoctrineOrmFaker
    mucho_mas_facil_in_page_edit.faker.class: MuchoMasFacil\InPageEditBundle\Faker\Generator

services:
#    mucho_mas_facil_in_page_edit.example:
#        class: %mucho_mas_facil_in_page_edit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mucho_mas_facil_in_page_edit.twig.ipe_extension:
        class: %mucho_mas_facil_in_page_edit.twig.ipe_extension.class%
        arguments: [@session, @translator, @fragment.handler, %mucho_mas_facil_in_page_edit.definitions%, %mucho_mas_facil_in_page_edit.message_catalog%]
        tags:
            - {name: twig.extension}

    mucho_mas_facil_in_page_edit.twig.ipe_extension_doctrine_orm_faker:
        class: %mucho_mas_facil_in_page_edit.twig.ipe_extension.doctrine.orm.faker.class%
        arguments: [@service_container]
        tags:
            - {name: twig.extension}

    mucho_mas_facil_in_page_edit.doctrine.orm.faker:
        class: %mucho_mas_facil_in_page_edit.faker.class%
        scope: request
        calls:
            - [initOrmDoctrineFaker, ["@request", "@doctrine"]]
