parameters:

    mucho_mas_facil_in_page_edit.entity_custom_params:
        default:
            editor_roles: ROLE_USER 
            #those below can be customized in renderWithContainerAction call
            render_action: MuchoMasFacilInPageEditBundle:EntityAdmin:renderObject
            render_template: ~ # (guessed from class_name) [bundle_name]:EntityRender:[last part of entity class name]
            form_template: MuchoMasFacilInPageEditBundle:EntityAdmin:Includes/form_template.html.twig

        MuchoMasFacil\InPageEditBundle\Entity\Foo: ~          

    mucho_mas_facil_in_page_edit.content_definitions:
        default:
            content_entity_class: ~
            editor_roles: ROLE_USER
            is_collection: false
            max_collection_length: ~
            lorem_ipsum_items_in_collection: 5

        plain_text:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\PlainText
            lorem_ipsum_items_in_collection: 2

        multi_line_plain_text:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\MultiLinePlainText

        rich_text:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\RichText

        custom_rich_text:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\CustomRichText

        rich_text_header_and_custom_rich_text:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\RichTextHeaderAndCustomRichText

        plain_text_header_and_custom_rich_text:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\PlainTextHeaderAndCustomRichText

        image:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\Image

        advanced_image:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\AdvancedImage

        one_level_menu:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\MenuItem
            is_collection: true

        one_level_basic_menu:
            content_entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\BasicMenuItem
            is_collection: true

    mucho_mas_facil_in_page_edit.ckeditor_options:
        default: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Default';
            config.toolbar_Default =
            [
                ['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink','-','About']
            ];

        full: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Full';
        basic: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Basic';
        custom: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Custom';
            config.toolbar_Custom =
            [
                { name: 'document', items : [ 'Source','-','Templates' ] },
                { name: 'clipboard', items : [ 'Cut','Copy','PasteText','-','Undo','Redo' ] },
                { name: 'editing', items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] },
                { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                '/',
                { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-'
                 ,'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
                 '/',
                { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar' ] },
                { name: 'styles', items : [ 'Format' ] },
                { name: 'tools', items : [ 'Maximize', 'ShowBlocks','-','About' ] }
            ];


services:
#    mucho_mas_facil_in_page_edit.example:
#        class: %mucho_mas_facil_in_page_edit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

