parameters:

    mucho_mas_facil_in_page_edit.entity_custom_params:
        default:
            yml_params: '{}'
            editor_roles: ROLE_USER
            form_template: ~ # by default str_replace('\\Entity\\', '\\Form\\', $entity_class).'Type';
            orm: default
        'MuchoMasFacil\InPageEditBundle\Entity\Foo':
            orm: mmf_ie

    mucho_mas_facil_in_page_edit.content_orm: mmf_ie

    mucho_mas_facil_in_page_edit.content_definitions:
        default:
            yml_params: '{}'
            editor_roles: ROLE_USER
            admin_roles: ROLE_ADMIN
            is_collection: false
            collection_length: ~
            lorem_ipsum_items_in_collection: 5

        plain_text:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\PlainText                       
            render_template: MuchoMasFacilInPageEditBundle:RenderContent:PlainText.html.twig
            lorem_ipsum_items_in_collection: 2

        multi_line_plain_text:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\MultiLinePlainText
            render_template: MuchoMasFacilInPageEditBundle:RenderContent:MultilinePlainText.html.twig

        rich_text:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\RichText
            render_template: MuchoMasFacilInPageEditBundle:RenderContent:RichText.html.twig

        custom_rich_text:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\CustomRichText
            render_template: MuchoMasFacilInPageEditBundle:RenderContent:CustomRichText.html.twig

        rich_text_header_and_custom_rich_text:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\RichTextHeaderAndCustomRichText
            render_template: 'MuchoMasFacilInPageEditBundle:RenderContent:RichTextHeaderAndCustomRichText.html.twig'

        plain_text_header_and_custom_rich_text:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\PlainTextHeaderAndCustomRichText
            render_template: 'MuchoMasFacilInPageEditBundle:RenderContent:PlainTextHeaderAndCustomRichText.html.twig'

        image:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\Image
            render_template: 'MuchoMasFacilInPageEditBundle:RenderContent:Image.html.twig'

        advanced_image:
            entity_class: MuchoMasFacil\InPageEditBundle\Entity\Contents\AdvancedImage
            render_template: 'MuchoMasFacilInPageEditBundle:RenderContent:AdvancedImage.html.twig'

    mucho_mas_facil_in_page_edit.ckeditor_options:
        default: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Default';
            config.toolbar_Default =
            [
                ['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink','-','About']
            ];

        full: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Full';
        basic: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Basic';
        custom: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Custom';
            config.toolbar_Custom =
            [
                { name: 'document', items : [ 'Source','-','Templates' ] },
                { name: 'clipboard', items : [ 'Cut','Copy','PasteText','-','Undo','Redo' ] },
                { name: 'editing', items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] },
                { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                '/',
                { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-'
                 ,'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
                 '/',
                { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar' ] },
                { name: 'styles', items : [ 'Format' ] },
                { name: 'tools', items : [ 'Maximize', 'ShowBlocks','-','About' ] }
            ];


services:
#    mucho_mas_facil_in_page_edit.example:
#        class: %mucho_mas_facil_in_page_edit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

