parameters:

    mucho_mas_facil_in_page_edit.available_langs:
        en: {label: English}
        es: {label: Español}

    mucho_mas_facil_in_page_edit.twig.ipe_extension.class: MuchoMasFacil\InPageEditBundle\Twig\IpeExtension

services:
#    mucho_mas_facil_in_page_edit.example:
#        class: %mucho_mas_facil_in_page_edit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mucho_mas_facil_in_page_edit.twig.ipe_extension:
        class: %mucho_mas_facil_in_page_edit.twig.ipe_extension.class%
        arguments: [@service_container]
        tags:
            - {name: twig.extension}

