parameters:

    mucho_mas_facil_in_page_edit.entity_custom_params:
        default:
            editor_roles: ROLE_USER #this one cannot be customized in renderWithContainer
            
            render_action: MuchoMasFacilInPageEditBundle:EntityAdmin:renderObject
            render_template: ~ # (guessing from class_name) MuchoMasFacilInPageEditBundle:EntityRender:Foo
            form_template: MuchoMasFacilInPageEditBundle:EntityAdmin:Includes/form_template.html.twig

        MuchoMasFacil\InPageEditBundle\Entity\Foo: ~
            
    mucho_mas_facil_in_page_edit.content_orm: mmf_ie

    mucho_mas_facil_in_page_edit.content_definitions:
        default:
            editor_roles: ROLE_USER
            admin_roles: ROLE_ADMIN
            is_collection: false
            collection_length: ~
            lorem_ipsum_items_in_collection: 5

        plain_text:
            entity_class: MuchoMasFacilInPageEditBundle:PlainText                       
            lorem_ipsum_items_in_collection: 2

        multi_line_plain_text:
            entity_class: MuchoMasFacilInPageEditBundle:MultiLinePlainText

        rich_text:
            entity_class: MuchoMasFacilInPageEditBundle:RichText

        custom_rich_text:
            entity_class: MuchoMasFacilInPageEditBundle:CustomRichText

        rich_text_header_and_custom_rich_text:
            entity_class: MuchoMasFacilInPageEditBundle:RichTextHeaderAndCustomRichText

        plain_text_header_and_custom_rich_text:
            entity_class: MuchoMasFacilInPageEditBundle:PlainTextHeaderAndCustomRichText

        image:
            entity_class: MuchoMasFacilInPageEditBundle:Image

        advanced_image:
            entity_class: MuchoMasFacilInPageEditBundle:AdvancedImage

        one_level_menu:
            entity_class: MuchoMasFacilInPageEditBundle:MenuItem
            is_collection: true

        one_level_basic_menu:
            entity_class: MuchoMasFacilInPageEditBundle:BasicMenuItem
            is_collection: true

    mucho_mas_facil_in_page_edit.ckeditor_options:
        default: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Default';
            config.toolbar_Default =
            [
                ['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink','-','About']
            ];

        full: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Full';
        basic: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Basic';
        custom: |
            config.forcePasteAsPlainText = true;
            config.toolbar = 'Custom';
            config.toolbar_Custom =
            [
                { name: 'document', items : [ 'Source','-','Templates' ] },
                { name: 'clipboard', items : [ 'Cut','Copy','PasteText','-','Undo','Redo' ] },
                { name: 'editing', items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] },
                { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
                '/',
                { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-'
                 ,'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
                 '/',
                { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar' ] },
                { name: 'styles', items : [ 'Format' ] },
                { name: 'tools', items : [ 'Maximize', 'ShowBlocks','-','About' ] }
            ];


services:
#    mucho_mas_facil_in_page_edit.example:
#        class: %mucho_mas_facil_in_page_edit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

