<?php

namespace MuchoMasFacil\InPageEditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooRepository extends EntityRepository
{

    public function fake($locale, $number = 1, $customColumnFormatters = array(), $customModifiers = array(), $generateId = false)
    {
        $em = $this->getEntityManager();           
        $generator = \Faker\Factory::create($locale);
        $populator = new \Faker\ORM\Doctrine\Populator($generator, $em);
        $populator->addEntity($this->getEntityName(), $number, $customColumnFormatters, $customModifiers, $generateId);
        $results = $populator->execute(); 
/*
//var_dump($results);
array(1) {
  ["MuchoMasFacil\InPageEditBundle\Entity\Foo"]=>
  array(1) {
    [0]=>object(MuchoMasFacil\InPageEditBundle\Entity\Fo
*/    
        return $results[$this->getEntityName()]; 
    }

}
