<?php

namespace MuchoMasFacil\InPageEditBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupedSortedObjectCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupedSortedObjectCollectionRepository extends EntityRepository
{

}
